name: oto_app_ia
description: Une interface unifiée pour accéder à une multitude de modèles d'intelligence artificielle open source.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  go_router: ^10.0.0
  dio: ^5.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_animate: ^4.2.0
  google_fonts: ^5.1.0
  flutter_markdown: ^0.6.17
  shared_preferences: ^2.2.0
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
